Added ssh test, fixed tar bug, testing traf user
1. Added ssh test to make sure able to connect

2. Fixed tar bug when running installer from other directory than
/installer/

3. Testing to make sure user is not running trafodion_installer from
the trafodion user id.

4. Added message to make sure user checks their firewall settings
if they can not access Hadoop.

Change-Id: I967c94ff23a0f0d55a1ca3a8ec7d51b7fb48307f

diff --git a/installer/traf_config_setup b/installer/traf_config_setup
--- a/installer/traf_config_setup
+++ b/installer/traf_config_setup
@@ -134,11 +134,6 @@ if [ -f $LOCAL_TRAF_CONFIG ]; then
 	source $LOCAL_TRAF_CONFIG
 fi
 
-if [[ "$(whoami)" == "$TRAF_USER" ]]; then
-   echo "***ERROR: The Trafodion username cannot be the same as the install username"
-   exit -1 
-fi
-
 echo "#!/bin/bash" > $LOCAL_TRAF_CONFIG
 echo "export TRAF_USER=\"$TRAF_USER\"" >> $LOCAL_TRAF_CONFIG
 echo "export TRAF_WORKDIR=\"$TRAF_WORKDIR\"" >> $LOCAL_TRAF_CONFIG
@@ -178,6 +173,15 @@ if [[ -z "$answer" ]]; then
       echo "***ERROR: Must enter list of nodes."
       exit -1
    fi 
+   for node in $NODE_LIST
+   do
+      ssh -n $node echo "***INFO: Testing ssh on $node"
+      if [[ $? -ne "0" ]]; then
+          echo "***ERROR: Could not ssh to $node."
+          echo "***ERROR: Check permissions and known hosts files."
+          exit -1
+      fi
+   done
 else
    NODES="$answer"
    NODE_LIST=""
@@ -199,6 +203,13 @@ else
          exit -1
       fi
 
+      ssh -n $newNode echo "***INFO: Testing ssh on $newNode"
+      if [[ $? -ne "0" ]]; then
+         echo "***ERROR: Could not ssh to $newNode."
+         echo "***ERROR: Please check node names for typos"
+         exit -1
+      fi
+
       if [[ "$newNode" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
          echo "***ERROR: Nodes are not named properly."
          echo "***ERROR: IP addresses are not supported. Please use node names."
@@ -206,9 +217,9 @@ else
       fi
     
       #Testing sudo access on all nodes
-      ssh -n $node sudo echo "***INFO: Testing sudo access on node $node"
+      ssh -n $newNode sudo echo "***INFO: Testing sudo access on $newNode"
       if [ $? -ne "0" ]; then
-         echo "***ERROR: Node $node does not have sudo access."
+         echo "***ERROR: Node $newNode does not have sudo access."
          echo "***ERROR: Must have sudo access on all nodes."
          exit -1
       fi
@@ -455,10 +466,10 @@ if [[ -z $TRAF_BUILD ]]; then
    exit -1
 fi
 
-install_features_path=$(tar -tf $TRAF_BUILD | grep "install_features")
+install_features_path=$(tar -tf $LOCAL_WORKDIR/$TRAF_BUILD | grep "install_features")
 
 if [[ ! -z $install_features_path ]]; then
-   tar -xzf $TRAF_BUILD $install_features_path
+   tar -xzf $LOCAL_WORKDIR/$TRAF_BUILD $install_features_path
    source $install_features_path
    echo "export CDH_5_3_HDP_2_2_SUPPORT=\"$CDH_5_3_HDP_2_2_SUPPORT\"" >> $LOCAL_TRAF_CONFIG
 else
@@ -643,11 +654,14 @@ if [ -z $CLUSTER_NAME ]; then
       if [ -x $CLUSTER_NAME ]; then
          echo "***ERROR: Could not access http://$URL" 2>&1 | tee -a $INSTALL_LOG
          echo "***ERROR: Check URL and port are correct or if Cloudera manager is up" 2>&1 | tee -a $INSTALL_LOG
+         echo "***ERROR: Check if iptables/firewall is configured correctly and ports are enabled."  2>&1 | tee -a $INSTALL_LOG 
          exit -1
       fi
    else 
       echo "***ERROR: Could not access http://$URL" 2>&1 | tee -a $INSTALL_LOG
       echo "***ERROR: Check URL and port are correct or if $hadoop_type is up." 2>&1 | tee -a $INSTALL_LOG
+      echo "***ERROR: Check if iptables/firewall is configured correctly and ports a
+    re enabled."  2>&1 | tee -a $INSTALL_LOG
       exit -1
    fi
 fi
